#!/usr/bin/env python3
# ---------------------------------------------------------
# Auto-generated by WebCure
# Recorded at: 2026-03-08T00:13:03.968Z
#
# Prerequisites:
#   1. pip install <path-to-webcure>/python
#   2. In VS Code/Cursor: Command Palette → "WebCure: Start API Server"
# ---------------------------------------------------------

from webcure import click, close_browser, navigate, resize_browser, type_text

navigate("https://demo.testfire.net")
resize_browser("fullscreen")
click("ONLINE BANKING LOGIN")
type_text("admin", into="#uid")
type_text("admin", into="#passw")
click("#login > table > tbody > tr:nth-child(3) > td:nth-child(2) > input[type=submit]")
click("#btnGetAccount")
close_browser()
