"""
WebCure Python client — convenience functions for recorded scripts.

Usage (auto-generated scripts):
    from webcure import navigate, click, type_text

Usage (class-based):
    from webcure import WebCure
    wc = WebCure(port=5678)
    wc.navigate("https://example.com")
"""

from webcure.client import WebCure

# Module-level client instance (lazy-initialized on first call)
_client: WebCure | None = None


def _get_client() -> WebCure:
    global _client
    if _client is None:
        _client = WebCure()
    return _client


def set_port(port: int) -> None:
    """Change the API server port (default: 5678)."""
    global _client
    _client = WebCure(port=port)


# ---------------------------------------------------------------------------
# Convenience functions — match the names generated by script-generator.ts
# ---------------------------------------------------------------------------

def launch_browser(url: str | None = None, headless: bool = False, browser: str = "chromium"):
    return _get_client().invoke("launchBrowser", {"url": url, "headless": headless, "browser": browser})


def close_browser():
    return _get_client().invoke("close", {})


def navigate(url: str, wait_until: str | None = None):
    args: dict = {"url": url}
    if wait_until:
        args["waitUntil"] = wait_until
    return _get_client().invoke("navigate", args)


def click(target: str, **kwargs):
    args: dict = {"text": target, "element": target}
    args.update(_parse_spatial(kwargs))
    return _get_client().invoke("click", args)


def double_click(target: str, **kwargs):
    args: dict = {"text": target, "element": target, "double": True}
    args.update(_parse_spatial(kwargs))
    return _get_client().invoke("click", args)


def right_click(target: str, **kwargs):
    args: dict = {"text": target, "element": target, "button": "right"}
    args.update(_parse_spatial(kwargs))
    return _get_client().invoke("click", args)


def type_text(text: str, into: str | None = None, **kwargs):
    args: dict = {"value": text}
    if into:
        args["text"] = into
        args["element"] = into
    args.update(_parse_spatial(kwargs))
    return _get_client().invoke("type", args)


def press_key(key: str):
    return _get_client().invoke("pressKey", {"key": key})


def hover(target: str, **kwargs):
    args: dict = {"text": target, "element": target}
    args.update(_parse_spatial(kwargs))
    return _get_client().invoke("hover", args)


def scroll_down(pixels: int = 300):
    return _get_client().invoke("scrollDown", {"pixels": pixels})


def scroll_up(pixels: int = 300):
    return _get_client().invoke("scrollUp", {"pixels": pixels})


def scroll_right(pixels: int = 300):
    return _get_client().invoke("scrollRight", {"pixels": pixels})


def scroll_left(pixels: int = 300):
    return _get_client().invoke("scrollLeft", {"pixels": pixels})


def refresh():
    return _get_client().invoke("refresh", {})


def go_back():
    return _get_client().invoke("navigateBack", {})


def go_forward():
    return _get_client().invoke("goForward", {})


def select_option(combo_box: str, value: str):
    return _get_client().invoke("select", {"text": combo_box, "values": [value]})


def switch_window(title: str):
    return _get_client().invoke("switchWindow", {"title": title})


def screenshot(path: str | None = None, full_page: bool = False):
    args: dict = {"fullPage": full_page}
    if path:
        args["outputPath"] = path
    return _get_client().invoke("screenshot", args)


def resize_browser(preset_or_width=None, height: int | None = None):
    if preset_or_width == "fullscreen":
        return _get_client().invoke("resize", {"preset": "fullscreen"})
    if isinstance(preset_or_width, int) and height is not None:
        return _get_client().invoke("resize", {"width": preset_or_width, "height": height})
    if isinstance(preset_or_width, str):
        return _get_client().invoke("resize", {"preset": preset_or_width})
    return _get_client().invoke("resize", {})


def fullscreen_browser():
    return _get_client().invoke("resize", {"preset": "fullscreen"})


def snapshot():
    return _get_client().invoke("snapshot", {})


def find(text: str | None = None, selector: str | None = None, **kwargs):
    args: dict = {}
    if text:
        args["text"] = text
    if selector:
        args["selector"] = selector
    args.update(_parse_spatial(kwargs))
    return _get_client().invoke("find", args)


def interact(action: str, ref: str | None = None, text: str | None = None,
             selector: str | None = None, value: str | None = None, **kwargs):
    args: dict = {"action": action}
    if ref:
        args["ref"] = ref
    if text:
        args["text"] = text
    if selector:
        args["selector"] = selector
    if value:
        args["value"] = value
    args.update(_parse_spatial(kwargs))
    return _get_client().invoke("interact", args)


def evaluate(expression: str, ref: str | None = None):
    args: dict = {"function": expression}
    if ref:
        args["ref"] = ref
    return _get_client().invoke("evaluate", args)


def extract(selector: str | None = None, max_length: int | None = None):
    args: dict = {}
    if selector:
        args["selector"] = selector
    if max_length:
        args["maxLength"] = max_length
    return _get_client().invoke("extract", args)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _parse_spatial(kwargs: dict) -> dict:
    spatial: dict = {}
    for k, v in kwargs.items():
        if k == "below":
            spatial["below"] = v
        elif k == "above":
            spatial["above"] = v
        elif k == "right_of":
            spatial["toRightOf"] = v
        elif k == "left_of":
            spatial["toLeftOf"] = v
        elif k == "near":
            spatial["near"] = v
    return spatial
