// ---------------------------------------------------------------------------
// WebCure -- Python script generator from recorded actions
// ---------------------------------------------------------------------------

import type { RecordedAction } from '../types';

/**
 * Convert a list of recorded actions into a Python script string.
 */
export function generatePythonScript(actions: RecordedAction[]): string {
    const lines: string[] = [];

    lines.push('#!/usr/bin/env python3');
    lines.push('# ---------------------------------------------------------');
    lines.push('# Auto-generated by WebCure');
    lines.push(`# Recorded at: ${new Date().toISOString()}`);
    lines.push('# ---------------------------------------------------------');
    lines.push('');

    const imports = collectImports(actions);
    if (imports.length > 0) {
        lines.push(`from webcure import ${imports.join(', ')}`);
        lines.push('');
    }

    for (const action of actions) {
        const pythonLine = actionToPython(action);
        if (pythonLine) {
            lines.push(pythonLine);
        }
    }

    lines.push('');
    return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Command-to-Python mapping
// ---------------------------------------------------------------------------

const COMMAND_TO_PYTHON: Record<string, string> = {
    launchBrowser: 'launch_browser',
    closeBrowser: 'close_browser',
    close: 'close_browser',
    navigate: 'navigate',
    click: 'click',
    doubleClick: 'double_click',
    rightClick: 'right_click',
    typeText: 'type_text',
    pressKey: 'press_key',
    hover: 'hover',
    scrollDown: 'scroll_down',
    scrollUp: 'scroll_up',
    scrollRight: 'scroll_right',
    scrollLeft: 'scroll_left',
    refresh: 'refresh',
    goBack: 'go_back',
    goForward: 'go_forward',
    navigateBack: 'go_back',
    selectOption: 'select_option',
    switchWindow: 'switch_window',
    screenshot: 'screenshot',
    resizeBrowser: 'resize_browser',
    fullscreenBrowser: 'fullscreen_browser',
    resize: 'resize_browser',
};

function actionToPython(action: RecordedAction): string | null {
    const fnName = COMMAND_TO_PYTHON[action.command];
    if (!fnName) {
        return `# (skipped: ${action.command})`;
    }
    const argParts = buildPythonArgs(action.command, action.args);
    return `${fnName}(${argParts})`;
}

function buildPythonArgs(command: string, args: Record<string, unknown>): string {
    switch (command) {
        case 'launchBrowser': {
            const parts: string[] = [];
            if (args.url) parts.push(pyStr(args.url));
            if (args.headless) parts.push('headless=True');
            return parts.join(', ');
        }
        case 'navigate':
            return args.url ? pyStr(args.url) : (args.target ? pyStr(args.target) : '');
        case 'click':
        case 'doubleClick':
        case 'rightClick':
        case 'hover':
            return args.target ? pyStr(args.target) : (args.ref ? pyStr(args.ref) : '');
        case 'pressKey':
            return args.key ? pyStr(args.key) : '';
        case 'switchWindow':
            return args.title ? pyStr(args.title) : '';
        case 'typeText': {
            const parts = [pyStr(args.text)];
            if (args.into) parts.push(`into=${pyStr(args.into)}`);
            return parts.join(', ');
        }
        case 'selectOption':
            return `${pyStr(args.comboBox)}, ${pyStr(args.value)}`;
        case 'scrollDown':
        case 'scrollUp':
        case 'scrollRight':
        case 'scrollLeft':
            return args.pixels ? String(args.pixels) : '';
        case 'screenshot':
            return args.path ? pyStr(args.path) : (args.outputPath ? pyStr(args.outputPath) : '');
        case 'resizeBrowser':
        case 'resize': {
            if (args.preset) return pyStr(args.preset);
            return `${args.width}, ${args.height}`;
        }
        case 'fullscreenBrowser':
            return '';
        default:
            return '';
    }
}

function collectImports(actions: RecordedAction[]): string[] {
    const names = new Set<string>();
    for (const action of actions) {
        const pyName = COMMAND_TO_PYTHON[action.command];
        if (pyName) {
            names.add(pyName);
        }
    }
    return Array.from(names).sort();
}

function pyStr(value: unknown): string {
    const s = String(value);
    return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}
