#!/usr/bin/env python3
# Auto-generated by WebCure Step Recorder
# Recorded at: 2026-03-29T00:00:00.000Z
#
# Prerequisites:
#   pip install playwright
#   playwright install chromium
#
# Run:  python3 test_recording.py

import re
import sys
import time
import logging
from datetime import datetime
from playwright.sync_api import sync_playwright, TimeoutError as PWTimeoutError

# ---------------------------------------------------------------------------
# Logging setup
# ---------------------------------------------------------------------------
_log_filename = f"test_results_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(message)s",
    datefmt="%H:%M:%S",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(_log_filename, mode='w'),
    ],
)
_logger = logging.getLogger("WebCure")
_step_results: list = []  # [(step_num, description, "PASS"|"FAIL", error_msg)]


def _record_step(step_num: int, description: str, passed: bool, error: str = ""):
    status = "PASS" if passed else "FAIL"
    _step_results.append((step_num, description, status, error))
    icon = "\u2705" if passed else "\u274C"
    msg = f"{icon}  Step {step_num}: {description} — {status}"
    if error:
        msg += f"  [{error}]"
    _logger.info(msg)


def _print_summary():
    total = len(_step_results)
    passed = sum(1 for r in _step_results if r[2] == "PASS")
    failed = total - passed
    _logger.info("")
    _logger.info("=" * 60)
    _logger.info(f"TEST SUMMARY: {passed}/{total} steps passed, {failed} failed")
    _logger.info("=" * 60)
    if failed:
        _logger.info("Failed steps:")
        for num, desc, status, err in _step_results:
            if status == "FAIL":
                _logger.info(f"  Step {num}: {desc}")
                _logger.info(f"    Error: {err}")
    _logger.info(f"Full log saved to: {_log_filename}")
    _logger.info("=" * 60)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
WAIT_TIMEOUT = 5000  # ms — max time to wait for any locator to become visible


# ---------------------------------------------------------------------------
# Self-healing locator resolution
# ---------------------------------------------------------------------------
def _resolve_locator(page, strategy: str, value: str):
    """Convert a (strategy, value) pair to a Playwright Locator object."""
    if strategy == "testId":
        m = re.search(r'"([^"]+)"', value)
        return page.get_by_test_id(m.group(1) if m else value)
    elif strategy == "id":
        return page.locator(f"#{value}")
    elif strategy == "aria":
        m = re.match(r'^([\w][\w-]*)\[name="([^"]+)"\]$', value)
        if m:
            return page.get_by_role(m.group(1), name=m.group(2))
        return page.locator(f'[aria-label="{value}"]')
    elif strategy == "ariaLabel":
        return page.get_by_label(value)
    elif strategy == "linkText":
        return page.get_by_role("link", name=value)
    elif strategy == "text":
        return page.get_by_text(value, exact=True)
    elif strategy == "name":
        return page.locator(f'[name="{value}"]')
    elif strategy == "css":
        return page.locator(value)
    elif strategy == "xpath":
        return page.locator(f"xpath={value}")
    else:
        return page.locator(value)


def find_element(page, locators: list, timeout: int = WAIT_TIMEOUT, state: str = "visible"):
    """
    Try each locator strategy in confidence order.
    Returns the first locator whose element is in *state* within *timeout* ms.
    Raises an Exception if none succeed.
    """
    last_err = None
    ordered = sorted(locators, key=lambda l: l.get("confidence", 0), reverse=True)
    for loc in ordered:
        strategy = loc.get("strategy", "css")
        value = loc.get("value", "")
        if not value:
            continue
        try:
            el = _resolve_locator(page, strategy, value)
            el.wait_for(state=state, timeout=timeout)
            return el
        except PWTimeoutError as e:
            last_err = e
        except Exception as e:
            last_err = e
    strategies = [f"{l.get('strategy')}={l.get('value')}" for l in ordered]
    raise Exception(f"Element not found with any of: {strategies}\nLast error: {last_err}")


def self_healing_click(page, locators: list, timeout: int = WAIT_TIMEOUT):
    """Find the element via self-healing locators then click it."""
    el = find_element(page, locators, timeout)
    el.click()


def self_healing_fill(page, locators: list, value: str, timeout: int = WAIT_TIMEOUT):
    """Find the element via self-healing locators then fill it with *value*."""
    el = find_element(page, locators, timeout)
    el.fill(value)


def self_healing_select(page, locators: list, value: str, timeout: int = WAIT_TIMEOUT):
    """Find the <select> element and choose the matching option."""
    el = find_element(page, locators, timeout)
    try:
        el.select_option(label=value)
    except Exception:
        el.select_option(value=value)


def self_healing_press(page, locators: list, key: str, timeout: int = WAIT_TIMEOUT):
    """Find the element via self-healing locators then press *key*."""
    el = find_element(page, locators, timeout)
    el.press(key)


def upload_file(page, locators: list, file_path: str, timeout: int = WAIT_TIMEOUT):
    """Upload a file to an <input type="file"> element using self-healing locators."""
    if not locators:
        locators = [{"strategy": "css", "value": 'input[type="file"]', "confidence": 0.5}]
    el = find_element(page, locators, timeout, state="attached")
    el.set_input_files(file_path)


# ---------------------------------------------------------------------------
# Self-healing assertion helpers
# ---------------------------------------------------------------------------
def assert_element_visible(page, locators: list, timeout: int = WAIT_TIMEOUT):
    """Assert that the element resolved by self-healing locators is visible."""
    el = find_element(page, locators, timeout)
    assert el.is_visible(), "Expected element to be visible"


def assert_element_not_visible(page, locators: list, timeout: int = 2000):
    """Assert that no element matching the locators is visible."""
    last_err = None
    ordered = sorted(locators, key=lambda l: l.get("confidence", 0), reverse=True)
    for loc in ordered:
        strategy = loc.get("strategy", "css")
        value = loc.get("value", "")
        if not value:
            continue
        try:
            el = _resolve_locator(page, strategy, value)
            el.wait_for(state="hidden", timeout=timeout)
            return
        except Exception as e:
            last_err = e
    if last_err:
        return


def assert_element_text(page, locators: list, expected_text: str, timeout: int = WAIT_TIMEOUT):
    """Assert that the element's text content contains the expected text (whitespace-normalized)."""
    el = find_element(page, locators, timeout)
    actual = re.sub(r'\s+', ' ', el.inner_text()).strip()
    expected = re.sub(r'\s+', ' ', expected_text).strip()
    assert expected in actual, f"Expected text '{expected}' in '{actual[:200]}'"


def assert_element_value(page, locators: list, expected_value: str, timeout: int = WAIT_TIMEOUT):
    """Assert that the input element's value matches."""
    el = find_element(page, locators, timeout)
    actual = el.input_value()
    assert actual == expected_value, f"Expected value '{expected_value}' but got '{actual}'"


def assert_element_checked(page, locators: list, expected: bool = True, timeout: int = WAIT_TIMEOUT):
    """Assert that a checkbox/radio is checked (or unchecked if expected=False)."""
    el = find_element(page, locators, timeout)
    actual = el.is_checked()
    state = "checked" if expected else "unchecked"
    assert actual == expected, f"Expected element to be {state} but it was {'checked' if actual else 'unchecked'}"


def assert_element_enabled(page, locators: list, expected: bool = True, timeout: int = WAIT_TIMEOUT):
    """Assert that the element is enabled (or disabled if expected=False)."""
    el = find_element(page, locators, timeout)
    actual = el.is_enabled()
    state = "enabled" if expected else "disabled"
    assert actual == expected, f"Expected element to be {state} but it was {'enabled' if actual else 'disabled'}"


def assert_page_title(page, expected_title: str):
    """Assert that the page title matches."""
    actual = page.title()
    assert actual == expected_title, f"Expected title '{expected_title}' but got '{actual}'"


def assert_page_url(page, expected_url: str, match_type: str = "exact"):
    """Assert that the page URL matches (exact or contains)."""
    actual = page.url
    if match_type == "contains":
        assert expected_url in actual, f"Expected URL to contain '{expected_url}' but got '{actual}'"
    else:
        assert actual == expected_url, f"Expected URL '{expected_url}' but got '{actual}'"


def assert_element_count(page, locators: list, expected_count: int, timeout: int = WAIT_TIMEOUT):
    """Assert that the number of elements matching the best locator equals expected_count."""
    ordered = sorted(locators, key=lambda l: l.get("confidence", 0), reverse=True)
    for loc in ordered:
        strategy = loc.get("strategy", "css")
        value = loc.get("value", "")
        if not value:
            continue
        try:
            el = _resolve_locator(page, strategy, value)
            el.first.wait_for(state="visible", timeout=timeout)
            actual = el.count()
            assert actual == expected_count, f"Expected {expected_count} elements but found {actual}"
            return
        except AssertionError:
            raise
        except Exception:
            continue
    raise Exception("Could not count elements — none of the locators matched")


def assert_element_attribute(page, locators: list, attr_name: str, expected_value: str, timeout: int = WAIT_TIMEOUT):
    """Assert that the element's attribute has the expected value."""
    el = find_element(page, locators, timeout)
    actual = el.get_attribute(attr_name)
    assert actual == expected_value, f"Expected {attr_name}='{expected_value}' but got '{actual}'"


def assert_page_contains_text(page, expected_text: str, timeout: int = WAIT_TIMEOUT):
    """Assert that the page body contains the expected text."""
    page.get_by_text(expected_text, exact=False).first.wait_for(state="visible", timeout=timeout)


# ---------------------------------------------------------------------------
# Recorded test flow
# ---------------------------------------------------------------------------
def test_recorded_flow():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        page = browser.new_page()
        _has_failure = False

        # ═══════════════════════════════════════════════════════════════
        # FLOW 1: the-internet.herokuapp.com — Checkboxes
        # ═══════════════════════════════════════════════════════════════

        try:
            # Step 1: Navigate to checkboxes page
            page.goto("https://the-internet.herokuapp.com/checkboxes", wait_until="domcontentloaded", timeout=15000)
            page.wait_for_load_state("networkidle")
            _record_step(1, 'Navigate to https://the-internet.herokuapp.com/checkboxes', True)
        except Exception as _e:
            _record_step(1, 'Navigate to https://the-internet.herokuapp.com/checkboxes', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 2: Assert page title is 'The Internet'
            assert_page_title(page, "The Internet")
            _record_step(2, 'Assert page title is \'The Internet\'', True)
        except Exception as _e:
            _record_step(2, 'Assert page title is \'The Internet\'', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 3: Assert page URL matches
            assert_page_url(page, "https://the-internet.herokuapp.com/checkboxes", "exact")
            _record_step(3, 'Assert page URL is \'https://the-internet.herokuapp.com/checkboxes\'', True)
        except Exception as _e:
            _record_step(3, 'Assert page URL is \'https://the-internet.herokuapp.com/checkboxes\'', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 4: Assert heading 'Checkboxes' is visible
            assert_element_visible(page, [
                {"strategy": "css", "value": "h3", "confidence": 0.8},
            ])
            _record_step(4, 'Assert heading \'Checkboxes\' is visible', True)
        except Exception as _e:
            _record_step(4, 'Assert heading \'Checkboxes\' is visible', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 5: Assert heading text contains 'Checkboxes'
            assert_element_text(page, [
                {"strategy": "css", "value": "h3", "confidence": 0.8},
            ], "Checkboxes")
            _record_step(5, 'Assert heading text contains \'Checkboxes\'', True)
        except Exception as _e:
            _record_step(5, 'Assert heading text contains \'Checkboxes\'', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 6: Assert exactly 2 checkboxes exist
            assert_element_count(page, [
                {"strategy": "css", "value": "#checkboxes input[type='checkbox']", "confidence": 0.9},
            ], 2)
            _record_step(6, 'Assert exactly 2 checkboxes exist', True)
        except Exception as _e:
            _record_step(6, 'Assert exactly 2 checkboxes exist', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 7: Assert checkbox 1 is unchecked by default
            assert_element_checked(page, [
                {"strategy": "css", "value": "#checkboxes input:nth-child(1)", "confidence": 0.8},
            ], False)
            _record_step(7, 'Assert checkbox 1 is unchecked', True)
        except Exception as _e:
            _record_step(7, 'Assert checkbox 1 is unchecked', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 8: Assert checkbox 2 is checked by default
            assert_element_checked(page, [
                {"strategy": "css", "value": "#checkboxes input:nth-child(3)", "confidence": 0.8},
            ], True)
            _record_step(8, 'Assert checkbox 2 is checked', True)
        except Exception as _e:
            _record_step(8, 'Assert checkbox 2 is checked', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 9: Click checkbox 1 to check it
            self_healing_click(page, [
                {"strategy": "css", "value": "#checkboxes input:nth-child(1)", "confidence": 0.8},
            ])
            _record_step(9, 'Clicked checkbox 1', True)
        except Exception as _e:
            _record_step(9, 'Clicked checkbox 1', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 10: Assert checkbox 1 is now checked
            assert_element_checked(page, [
                {"strategy": "css", "value": "#checkboxes input:nth-child(1)", "confidence": 0.8},
            ], True)
            _record_step(10, 'Assert checkbox 1 is now checked after click', True)
        except Exception as _e:
            _record_step(10, 'Assert checkbox 1 is now checked after click', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 11: Assert non-existent element is not visible
            assert_element_not_visible(page, [
                {"strategy": "id", "value": "does-not-exist-xyz", "confidence": 0.9},
            ])
            _record_step(11, 'Assert non-existent element is not visible', True)
        except Exception as _e:
            _record_step(11, 'Assert non-existent element is not visible', False, str(_e)[:200])
            _has_failure = True

        # ═══════════════════════════════════════════════════════════════
        # FLOW 2: the-internet.herokuapp.com — Dropdown
        # ═══════════════════════════════════════════════════════════════

        try:
            # Step 12: Navigate to dropdown page
            page.goto("https://the-internet.herokuapp.com/dropdown", wait_until="domcontentloaded", timeout=15000)
            page.wait_for_load_state("networkidle")
            _record_step(12, 'Navigate to https://the-internet.herokuapp.com/dropdown', True)
        except Exception as _e:
            _record_step(12, 'Navigate to https://the-internet.herokuapp.com/dropdown', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 13: Assert dropdown is visible
            assert_element_visible(page, [
                {"strategy": "id", "value": "dropdown", "confidence": 0.95},
            ])
            _record_step(13, 'Assert dropdown is visible', True)
        except Exception as _e:
            _record_step(13, 'Assert dropdown is visible', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 14: Assert dropdown is enabled
            assert_element_enabled(page, [
                {"strategy": "id", "value": "dropdown", "confidence": 0.95},
            ], True)
            _record_step(14, 'Assert dropdown is enabled', True)
        except Exception as _e:
            _record_step(14, 'Assert dropdown is enabled', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 15: Select 'Option 2' from dropdown
            self_healing_select(page, [
                {"strategy": "id", "value": "dropdown", "confidence": 0.95},
            ], "Option 2")
            _record_step(15, 'Selected \'Option 2\' from dropdown', True)
        except Exception as _e:
            _record_step(15, 'Selected \'Option 2\' from dropdown', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 16: Assert dropdown value is '2'
            assert_element_value(page, [
                {"strategy": "id", "value": "dropdown", "confidence": 0.95},
            ], "2")
            _record_step(16, 'Assert dropdown value is \'2\'', True)
        except Exception as _e:
            _record_step(16, 'Assert dropdown value is \'2\'', False, str(_e)[:200])
            _has_failure = True

        # ═══════════════════════════════════════════════════════════════
        # FLOW 3: the-internet.herokuapp.com — Inputs
        # ═══════════════════════════════════════════════════════════════

        try:
            # Step 17: Navigate to inputs page
            page.goto("https://the-internet.herokuapp.com/inputs", wait_until="domcontentloaded", timeout=15000)
            page.wait_for_load_state("networkidle")
            _record_step(17, 'Navigate to https://the-internet.herokuapp.com/inputs', True)
        except Exception as _e:
            _record_step(17, 'Navigate to https://the-internet.herokuapp.com/inputs', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 18: Fill number input with '12345'
            self_healing_fill(page, [
                {"strategy": "css", "value": "input[type='number']", "confidence": 0.9},
            ], "12345")
            _record_step(18, 'Typed \'12345\' into number input', True)
        except Exception as _e:
            _record_step(18, 'Typed \'12345\' into number input', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 19: Assert input value is '12345'
            assert_element_value(page, [
                {"strategy": "css", "value": "input[type='number']", "confidence": 0.9},
            ], "12345")
            _record_step(19, 'Assert input value is \'12345\'', True)
        except Exception as _e:
            _record_step(19, 'Assert input value is \'12345\'', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 20: Assert input has attribute type='number'
            assert_element_attribute(page, [
                {"strategy": "css", "value": "input[type='number']", "confidence": 0.9},
            ], "type", "number")
            _record_step(20, 'Assert input has attribute type=\'number\'', True)
        except Exception as _e:
            _record_step(20, 'Assert input has attribute type=\'number\'', False, str(_e)[:200])
            _has_failure = True

        # ═══════════════════════════════════════════════════════════════
        # FLOW 4: demo.testfire.net — Login Flow with Assertions
        # ═══════════════════════════════════════════════════════════════

        try:
            # Step 21: Navigate to AltoroMutual login page
            page.goto("http://demo.testfire.net/login.jsp", wait_until="domcontentloaded", timeout=15000)
            page.wait_for_load_state("networkidle")
            _record_step(21, 'Navigate to http://demo.testfire.net/login.jsp', True)
        except Exception as _e:
            _record_step(21, 'Navigate to http://demo.testfire.net/login.jsp', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 22: Assert page URL contains 'login'
            assert_page_url(page, "login", "contains")
            _record_step(22, 'Assert page URL contains \'login\'', True)
        except Exception as _e:
            _record_step(22, 'Assert page URL contains \'login\'', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 23: Assert username input is visible
            assert_element_visible(page, [
                {"strategy": "id", "value": "uid", "confidence": 0.95},
                {"strategy": "name", "value": "uid", "confidence": 0.9},
            ])
            _record_step(23, 'Assert username input is visible', True)
        except Exception as _e:
            _record_step(23, 'Assert username input is visible', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 24: Assert password input is visible
            assert_element_visible(page, [
                {"strategy": "id", "value": "passw", "confidence": 0.95},
                {"strategy": "name", "value": "passw", "confidence": 0.9},
            ])
            _record_step(24, 'Assert password input is visible', True)
        except Exception as _e:
            _record_step(24, 'Assert password input is visible', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 25: Assert login button is enabled
            assert_element_enabled(page, [
                {"strategy": "name", "value": "btnSubmit", "confidence": 0.9},
                {"strategy": "css", "value": "input[type='submit']", "confidence": 0.8},
            ], True)
            _record_step(25, 'Assert login button is enabled', True)
        except Exception as _e:
            _record_step(25, 'Assert login button is enabled', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 26: Type 'admin' into username
            self_healing_fill(page, [
                {"strategy": "id", "value": "uid", "confidence": 0.95},
                {"strategy": "name", "value": "uid", "confidence": 0.9},
            ], "admin")
            _record_step(26, 'Typed \'admin\' into username', True)
        except Exception as _e:
            _record_step(26, 'Typed \'admin\' into username', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 27: Assert username value is 'admin'
            assert_element_value(page, [
                {"strategy": "id", "value": "uid", "confidence": 0.95},
            ], "admin")
            _record_step(27, 'Assert username value is \'admin\'', True)
        except Exception as _e:
            _record_step(27, 'Assert username value is \'admin\'', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 28: Type 'admin' into password
            self_healing_fill(page, [
                {"strategy": "id", "value": "passw", "confidence": 0.95},
                {"strategy": "name", "value": "passw", "confidence": 0.9},
            ], "admin")
            _record_step(28, 'Typed \'admin\' into password', True)
        except Exception as _e:
            _record_step(28, 'Typed \'admin\' into password', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 29: Click Login button
            self_healing_click(page, [
                {"strategy": "name", "value": "btnSubmit", "confidence": 0.9},
                {"strategy": "css", "value": "input[type='submit']", "confidence": 0.8},
            ])
            page.wait_for_load_state("networkidle", timeout=10000)
            _record_step(29, 'Clicked Login button', True)
        except Exception as _e:
            _record_step(29, 'Clicked Login button', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 30: Assert page URL now contains 'bank' (redirected after login)
            assert_page_url(page, "bank", "contains")
            _record_step(30, 'Assert page URL contains \'bank\' after login', True)
        except Exception as _e:
            _record_step(30, 'Assert page URL contains \'bank\' after login', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 31: Assert page contains text 'Sign Off' (proves we are logged in)
            assert_page_contains_text(page, "Sign Off")
            _record_step(31, 'Assert page contains text \'Sign Off\'', True)
        except Exception as _e:
            _record_step(31, 'Assert page contains text \'Sign Off\'', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 32: Assert 'Hello Admin User' heading text
            assert_element_text(page, [
                {"strategy": "css", "value": "h1", "confidence": 0.8},
            ], "Hello Admin User")
            _record_step(32, 'Assert heading text contains \'Hello Admin User\'', True)
        except Exception as _e:
            _record_step(32, 'Assert heading text contains \'Hello Admin User\'', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 33: Assert 'Sign Off' link has correct href attribute
            assert_element_attribute(page, [
                {"strategy": "linkText", "value": "Sign Off", "confidence": 0.9},
            ], "href", "/logout.jsp")
            _record_step(33, 'Assert Sign Off link href is \'/logout.jsp\'', True)
        except Exception as _e:
            _record_step(33, 'Assert Sign Off link href is \'/logout.jsp\'', False, str(_e)[:200])
            _has_failure = True

        # ═══════════════════════════════════════════════════════════════
        # FLOW 5: Self-healing fallback — broken primary locator
        # ═══════════════════════════════════════════════════════════════

        try:
            # Step 34: Navigate back to login page
            page.goto("http://demo.testfire.net/login.jsp", wait_until="domcontentloaded", timeout=15000)
            page.wait_for_load_state("networkidle")
            _record_step(34, 'Navigate to http://demo.testfire.net/login.jsp', True)
        except Exception as _e:
            _record_step(34, 'Navigate to http://demo.testfire.net/login.jsp', False, str(_e)[:200])
            _has_failure = True

        try:
            # Step 35: Assert visible using fallback — first locator is broken, second works
            assert_element_visible(page, [
                {"strategy": "id", "value": "nonexistent-broken-id", "confidence": 0.99},
                {"strategy": "name", "value": "uid", "confidence": 0.5},
            ])
            _record_step(35, 'Assert element visible via self-healing fallback', True)
        except Exception as _e:
            _record_step(35, 'Assert element visible via self-healing fallback', False, str(_e)[:200])
            _has_failure = True

        _print_summary()
        browser.close()
        if _has_failure:
            sys.exit(1)


if __name__ == "__main__":
    test_recorded_flow()
